name: CI - Build, Test & Lint

on:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches:
      - main
      - develop
    types: [opened, synchronize]
    paths-ignore:
      - '**/*.md'

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: JDK 17 설정
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Gradle clean build 실행 (빌드, 테스트, lint 포함)
        run: ./gradlew clean build --stacktrace